# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SQL_DB_HOST: db
      SQL_DB_NAME: postgres
      SQL_DB_USER: postgres
      SQL_DB_PASSWORD: example4132
    ports:
      - "8080:8080"
    
  db:
    container_name: db
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example4132
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  jenkins:
    container_name: jenkins
    user: root
    privileged: true
    image: jenkins/jenkins:lts
    ports:
      - "8082:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
