# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
