#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER foo WITH ENCRYPTED PASSWORD 'foobar' SUPERUSER;
    CREATE DATABASE bar;
    GRANT ALL PRIVILEGES ON DATABASE bar TO foo;
EOSQL
